version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  ApplicationStart:
    - location: start_service.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_service.sh
      timeout: 300
      runas: root