server.port: 80
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_OVVV5amMh

cloud:
  aws:
    stack:
      auto: false