server.port: 80
server:
  ssl:
    enabled: false

dynamodb:
  endpoint: http://localhost:8000

cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false
    credentials:
      access-key: a_dummy_value_but_it_is_necessary
      secret-key: a_dummy_value_but_it_is_necessary